### Buscar todo os ID
GET http://localhost:3333/user

### Buscar ID especifico
GET http://localhost:3333/user/a05172be-8ce6-4e0b-b889-220177c06282

### Inserir Informação no banco
POST http://localhost:3333/user/
content-type: application/json

{
"name": "FEMA 2", "curso": "Tecnico em Informatica", "email":"fema@fema.com", "uc":"Programação WEB 3"
}

### Deletar um usuario do banco
DELETE http://localhost:3333/user/a05172be-8ce6-4e0b-b889-220177c06282

### Atualizar um usuário e um ID no Banco.

PUT http://localhost:3333/user/08005ae2-d0f1-4d89-a0dd-1259189e1a76
content-type: application/json

{
"name": "Adriano Silva Santos",
"email":"adriano.s.santos@fema.com"
}
