### Buscar todo os ID
GET http://localhost:3333

### Buscar ID especifico
GET http://localhost:3333/a05172be-8ce6-4e0b-b889-220177c06282

### Inserir Informação no banco
POST http://localhost:3333
content-type: application/json

{
"name": "FEMA 2", "curso": "Tecnico em Informatica", "email":"fema@fema.com", "uc":"Programação WEB 3"
}

### Deletar um usuario do banco
DELETE http://localhost:3333/a05172be-8ce6-4e0b-b889-220177c06282
